<?php

    function generate_report($report_id, $report_date, $patient_id, $patient_name, $patient_email, $patient_phone, $patient_address, $patient_age, $patient_gender, $hospital_id, $hospital_name, $hospital_email, $result) {

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        $payload_arr = array();
        $payload_arr['report_id'] = $report_id;
        $payload_arr['report_date'] = $report_date;
        $payload_arr['patient_id'] = $patient_id;
        $payload_arr['patient_name'] = $patient_name;
        $payload_arr['patient_email'] = $patient_email;
        $payload_arr['patient_phone'] = $patient_phone;
        $payload_arr['patient_address'] = $patient_address;
        $payload_arr['patient_age'] = $patient_age;
        $payload_arr['patient_gender'] = $patient_gender;
        $payload_arr['hospital_id'] = $hospital_id;
        $payload_arr['hospital_name'] = $hospital_name;
        $payload_arr['hospital_email'] = $hospital_email;
        $payload_arr['result'] = $result;

        $payload = json_encode($payload_arr);

        curl_setopt($ch, CURLOPT_URL, 'https://api.pdfmonkey.io/api/v1/documents');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n        \"document\": {\n          \"document_template_id\": \"8BE1BC97-DE60-486B-8C80-1D41B0C4F362\",\n          \"payload\": $payload,\n          \"status\": \"pending\"\n        }\n      }");

        $headers = array();
        $headers[] = 'Authorization: Bearer xuBpNEAWdK9V5tyA8Yvz';
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);

        echo $result;

        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        $result_arr = json_decode($result);

        echo print_r($result_arr);

        $doc_id =  $result_arr->document->id;

        sleep(10);


        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.pdfmonkey.io/api/v1/documents/' . $doc_id);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: Bearer xuBpNEAWdK9V5tyA8Yvz';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);

        echo $result;

        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        $result_arr = json_decode($result);
        // echo $result_arr->document->download_url;

        return $result_arr->document->download_url;

    }




?>